# Generated by Django 5.0.9 on 2024-10-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userpassword_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='password',
            field=models.CharField(default='123456', max_length=500),
        ),
    ]
